### ISSUE TITLE
Crash when missing reviews

### ISSUE THREAD

**Issue by redbassett** [redbassett/popwatch#6]
User reported crash when movies are lacking reviews.

```
06-18 03:46:45.972 26858-26883/com.redbassett.popwatch E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                         Process: com.redbassett.popwatch, PID: 26858
                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                             at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                             at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                             at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                             at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                             at com.redbassett.popwatch.MovieApi.TmdbApi.getMovieReviews(TmdbApi.java:122)
                                                                             at com.redbassett.popwatch.MovieDetailFragment$FetchReviewTask.doInBackground(MovieDetailFragment.java:349)
                                                                             at com.redbassett.popwatch.MovieDetailFragment$FetchReviewTask.doInBackground(MovieDetailFragment.java:343)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818)
```

**Comment by redbassett** [comment]
Unable to reproduce on Moto XT1094 running API 22. Given lack of information for device reporting the crash, fix appears to be just implementing checks for null content.

**Comment by redbassett** [comment]
The issue appears to have actually not been caused by a lack of reviews (which just returns an empty result, not a null JSON object), but an issue with how IDs were stored for just top-rated movies. See commit 27638437ab4e247c6e0e84719e35a68de6899d03 for more information.
